name: Sheduler
on:
  schedule:
    - cron: '10 18 * * *'
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 22f3000162@ds.study.iitm.ac.in
        run: echo "Hello, world!"
