name: Sheduler

on:
  schedule:
    - cron: '16 13 * * *'  # Runs at 13:00 UTC = 18:30 IST
  workflow_dispatch: 

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 22f3000162@ds.study.iitm.ac.in
        run: |
          git config user.name "auto-commit"
          git config user.email "22f3000162@ds.study.iitm.ac.in"

      - name: Make a dummy commit
        run: |
          echo "Run at $(date -u)" >> daily-log.txt
          git add daily-log.txt
          git commit -m "Daily commit"
          git push origin main
