name: Sheduler
on:
  schedule:
    - cron: '01 13 * * *'
jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 22f3000162@ds.study.iitm.ac.in
        run: |
          git config user.name "22f3000162"
          git config user.email "22f3000162@ds.study.iitm.ac.in"

      - name: Make commit
        run: |
          echo "commit" >> daily-log.txt
          git add daily-log.txt
          git commit -m "Daily commit"
          git push
